name: muslim_ia
description: "Muslim IA - Apprendre le Coran et l'Islam avec l'IA"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.1
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  webview_flutter: ^4.10.0
  geniuspay_flutter: ^1.0.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  firebase_messaging: ^15.1.0
  flutter_sound: ^9.2.13
  permission_handler: ^11.3.1
  flutter_localizations:
    sdk: flutter
  share_plus: ^13.3.0
  flutter_tts: ^4.2.3
  path_provider: ^2.1.4
  qr_flutter: ^4.1.0
  connectivity_plus: ^7.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/muslimia.jpeg
    - assets/terms_of_use.txt
    - assets/privacy_policy.txt

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/muslimia.jpeg"
  adaptive_icon_background: "#0F1B4C"
  adaptive_icon_foreground: "assets/muslimia.jpeg"
